[project]
name = "easy-gpt"
version = "0.2.1"
description = "Lightweight typed wrapper around the OpenAI Responses API"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "openai>=1.0.0",
]
keywords = ["openai", "assistant", "typing", "literal"]
license = {text = "MIT"}

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

