[project]
name = "easy-gpt"
version = "0.2.0"
description = "Lightweight typed wrapper around the OpenAI responses API"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "openai>=1.0.0",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

