name: Codex Auto-Fix on Issue

on:
  issues:
    types: [opened]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-fix:
    runs-on: ubuntu-latest
    env:
      ISSUE_NUMBER: ${{ github.event.issue.number }}
      ISSUE_TITLE: ${{ github.event.issue.title }}
      ISSUE_BODY: ${{ github.event.issue.body }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check OpenAI key
        run: |
          if [ -z "$OPENAI_API_KEY" ]; then
            echo "OPENAI_API_KEY not set; skipping auto-fix" >&2
            exit 1
          fi

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai PyGithub

      - name: Run auto-fix script
        id: run_fix
        run: |
          python .github/scripts/auto_fix_on_issue.py

      - name: Create PR if generated
        if: steps.run_fix.outputs.pr_number != ''
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "fix: auto patch via Codex"
          branch: codex/auto-fix-issue-${{ env.ISSUE_NUMBER }}
          base: main
          title: "Auto-fix issue #${{ env.ISSUE_NUMBER }}"
          body: |
            This PR was generated by Codex in response to issue #${{ env.ISSUE_NUMBER }}.
            Issue title: “${{ env.ISSUE_TITLE }}”
            Issue description:
            ```
            ${{ env.ISSUE_BODY }}
            ```
