name: Codex Auto PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  codex_review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # get full history for diff

      - name: Install Codex CLI
        run: npm install -g @openai/codex

      - name: Generate review with Codex
        id: review
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          # Fetch all branches so we can diff properly
          git fetch --all

          BASE_BRANCH="${{ github.event.pull_request.base.ref }}"
          HEAD_BRANCH="${{ github.event.pull_request.head.ref }}"

          echo "Comparing origin/$BASE_BRANCH...origin/$HEAD_BRANCH"

          # Make sure branches exist locally
          git fetch origin "$BASE_BRANCH":"$BASE_BRANCH"
          git fetch origin "$HEAD_BRANCH":"$HEAD_BRANCH"

          # Try to get diff; if not possible, fallback
          DIFF=$(git diff "origin/$BASE_BRANCH...origin/$HEAD_BRANCH" || echo "No diff available")

          PROMPT="You are Codex, a concise but sharp code reviewer. Review the following Git diff between $BASE_BRANCH and $HEAD_BRANCH.
Focus on clarity, correctness, and structure. Give specific, actionable feedback in markdown format. 
End your message with '**Score: <number>/10**' on its own line.\n\n$DIFF"

          echo "Sending diff to Codex..."
          OUTPUT=$(echo "$PROMPT" | npx codex)
          
          # Save Codex's output to env
          {
            echo "REVIEW<<EOF"
            echo "$OUTPUT"
            echo "EOF"
          } >> $GITHUB_ENV

      - name: Post Codex review comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
            -f body="${{ env.REVIEW }}"
