name: Auto Pull Request for bob/* branches

on:
  push:
    branches:
      - 'codex/**'

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install easy-pull-request
        run: pip install easy-pull-request

      - name: Create pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          branch_name="${GITHUB_REF##*/}"
          base_branch="main"

          echo "Creating PR from $branch_name to $base_branch"
          easy-pull-request \
            --head "$branch_name" \
            --base "$base_branch" \
            --title "Auto PR: $branch_name" \
            --body "This PR was automatically created for branch $branch_name" \
            --token "$GITHUB_TOKEN" \
            --no-force
