name: Codex Auto PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  codex_review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Install Codex CLI
        run: npm install -g @openai/codex

      - name: Generate review with Codex
        id: review
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          DIFF=$(git fetch origin main && git diff origin/main...HEAD)
          PROMPT="Review the following pull request diff. Give constructive feedback in markdown, focusing on code quality, readability, and potential bugs. End with a numeric score out of 10 labeled 'Score'.\n\n$DIFF"
          OUTPUT=$(echo "$PROMPT" | npx codex)
          echo "REVIEW<<EOF" >> $GITHUB_ENV
          echo "$OUTPUT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Post Codex review comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
            -f body="${{ env.REVIEW }}"
