name: Linter and Codex Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  lint-and-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -U pip setuptools wheel flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run flake8 linter
        id: lint
        run: |
          echo "body<<EOF" >> $GITHUB_OUTPUT
          echo '### 🧹 Flake8 Lint Report' >> $GITHUB_OUTPUT
          flake8 . || true | tee lint_report.txt
          if [ -s lint_report.txt ]; then
            echo "\`\`\`" >> $GITHUB_OUTPUT
            cat lint_report.txt >> $GITHUB_OUTPUT
            echo "\`\`\`" >> $GITHUB_OUTPUT
          else
            echo "✅ No lint errors found." >> $GITHUB_OUTPUT
          fi
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Comment lint results
        run: |
          gh api repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
            -f body="${{ steps.lint.outputs.body }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment Codex review trigger
        run: |
          gh api repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
            -f body="@codex review this pull request"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
